export enum CommunitiesTypes {
    FETCH_COMMUNITIES_REQUEST = 'FETCH_COMMUNITIES_REQUEST',
    FETCH_COMMUNITIES_SUCCESS = 'FETCH_COMMUNITIES_SUCCESS',
    CREATE_COMMUNITY = 'CREATE_COMMUNITY',
    UPDATE_COMMUNITY = 'UPDATE_COMMUNITY',
    DELETE_COMMUNITY = 'DELETE_COMMUNITY',
}